package kr.antos112.addnavigation.navigation;

import kr.antos112.addnavigation.AddNavigation;
import kr.antos112.addnavigation.api.NavigationSession;
import kr.antos112.addnavigation.model.NavigationSettings;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.entity.Display;
import org.bukkit.entity.ItemDisplay;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.util.Transformation;
import org.bukkit.util.Vector;
import org.joml.Quaternionf;
import org.joml.Vector3f;

import java.util.List;

/**
 * 다음 경로 경유지를 가리키는 플로팅 ItemDisplay 하나를 렌더링합니다.
 */
public final class ArrowTrailRenderer {
    private final AddNavigation plugin;
    private final NavigationSettings settings;
    private final ItemStack indicatorItem;

    /**
     * 플러그인 및 디스플레이 설정을 포함하는 렌더러를 생성합니다.
     *
     * @param plugin plugin instance
     * @param settings navigation display settings
     */
    public ArrowTrailRenderer(AddNavigation plugin, NavigationSettings settings) {
        this.plugin = plugin;
        this.settings = settings;
        this.indicatorItem = createIndicatorItem();
    }

    /**
     * 유저에게 표시되는 방향 표시기를 업데이트합니다.
     *
     * @param viewer player who should see the indicator
     * @param session active navigation session
     * @param path raw path points generated by the pathfinder
     */
    public void render(Player viewer, NavigationSession session, List<Location> path) {
        Location nextWaypoint = findNextWaypoint(viewer, session, path);
        if (nextWaypoint == null) {
            clearAll(session, viewer);
            return;
        }

        ItemDisplay indicator = session.getIndicator();
        if (indicator == null || !indicator.isValid() || !indicator.getWorld().equals(viewer.getWorld())) {
            removeIndicator(indicator, viewer);
            indicator = spawnIndicator(viewer.getWorld(), viewer.getLocation());
            session.setIndicator(indicator);
        }

        indicator.teleport(indicatorLocation(viewer, nextWaypoint));
        viewer.showEntity(plugin, indicator);
    }

    /**
     * 해당 세션에 대한 렌더링된 표시기를 제거합니다.
     *
     * @param session active session
     * @param viewer player who currently sees the indicator
     */
    public void clearAll(NavigationSession session, Player viewer) {
        removeIndicator(session.getIndicator(), viewer);
        session.setIndicator(null);
    }

    private ItemDisplay spawnIndicator(World world, Location location) {
        return world.spawn(location, ItemDisplay.class, display -> {
            configure(display);
            display.setVisibleByDefault(false);
            display.setGravity(false);
            display.setSilent(true);
            display.setPersistent(false);
            display.setBillboard(Display.Billboard.FIXED);
            display.setItemDisplayTransform(ItemDisplay.ItemDisplayTransform.FIXED);
            display.setTeleportDuration(1);
            display.setInterpolationDuration(1);
            display.setInterpolationDelay(0);
            display.setViewRange((float) settings.indicatorViewRange());
        });
    }

    private void configure(ItemDisplay display) {
        display.setItemStack(indicatorItem);
        display.setItemDisplayTransform(ItemDisplay.ItemDisplayTransform.FIXED);
        display.setBillboard(Display.Billboard.FIXED);
        display.setViewRange((float) settings.indicatorViewRange());
        display.setInterpolationDuration(1);
        display.setInterpolationDelay(0);
        display.setTeleportDuration(1);
        display.setDisplayWidth(0.8f);
        display.setDisplayHeight(0.8f);
        display.setPersistent(false);
        display.setVisibleByDefault(false);
        display.setGravity(false);
        display.setGlowing(settings.indicatorGlowing());
        float scale = (float) settings.indicatorScale();
        display.setTransformation(new Transformation(
                new Vector3f(),
                new Quaternionf().rotateX((float) Math.toRadians(settings.indicatorPitchOffset())),
                new Vector3f(scale, scale, scale),
                new Quaternionf()
        ));
    }

    private ItemStack createIndicatorItem() {
        ItemStack item = new ItemStack(settings.resolvedIndicatorMaterial());
        if (settings.indicatorCustomModelData() > 0) {
            ItemMeta meta = item.getItemMeta();
            if (meta != null) {
                meta.setCustomModelData(settings.indicatorCustomModelData());
                item.setItemMeta(meta);
            }
        }
        return item;
    }

    private Location findNextWaypoint(Player viewer, NavigationSession session, List<Location> path) {
        if (path == null || path.isEmpty()) {
            return null;
        }
        if (path.size() == 1) {
            return sameWorld(path.getFirst(), viewer) ? path.getFirst() : null;
        }

        Location playerLocation = viewer.getLocation();
        int progressIndex = Math.min(session.getPathProgressIndex(), path.size() - 2);
        progressIndex = advanceProgress(playerLocation, path, progressIndex);
        session.setPathProgressIndex(progressIndex);

        Location segmentStart = path.get(progressIndex);
        Location segmentEnd = path.get(progressIndex + 1);
        if (!sameWorld(segmentStart, viewer) || !sameWorld(segmentEnd, viewer)) {
            return null;
        }

        Location projected = projectOntoSegment(segmentStart, segmentEnd, playerLocation);
        return pointAhead(path, progressIndex, projected, settings.lookAheadDistance());
    }

    private int advanceProgress(Location playerLocation, List<Location> path, int progressIndex) {
        int current = Math.max(0, progressIndex);
        double advanceDistance = Math.max(1.0, settings.lookAheadDistance() * 0.75);
        double advanceDistanceSquared = advanceDistance * advanceDistance;

        while (current < path.size() - 2) {
            Location segmentStart = path.get(current);
            Location segmentEnd = path.get(current + 1);
            if (segmentStart == null || segmentEnd == null) {
                break;
            }

            double rawProjection = horizontalProjection(segmentStart, segmentEnd, playerLocation);
            if (rawProjection >= 1.0 || horizontalDistanceSquared(playerLocation, segmentEnd) <= advanceDistanceSquared) {
                current++;
                continue;
            }

            break;
        }

        return current;
    }

    private Location pointAhead(List<Location> path, int segmentIndex, Location projected, double lookAheadDistance) {
        double remaining = Math.max(0.25, lookAheadDistance);
        Location cursor = projected;

        for (int i = segmentIndex; i < path.size() - 1; i++) {
            Location end = path.get(i + 1);
            if (end == null || end.getWorld() == null || cursor.getWorld() == null || !end.getWorld().equals(cursor.getWorld())) {
                continue;
            }

            double segmentLength = horizontalDistance(cursor, end);
            if (segmentLength <= 0.0001) {
                cursor = end;
                continue;
            }

            if (segmentLength >= remaining) {
                return interpolate(cursor, end, remaining / segmentLength);
            }

            remaining -= segmentLength;
            cursor = end;
        }

        return cursor;
    }

    private Location projectOntoSegment(Location start, Location end, Location point) {
        double t = clamp(horizontalProjection(start, end, point));
        return interpolate(start, end, t);
    }

    private double horizontalProjection(Location start, Location end, Location point) {
        double dx = end.getX() - start.getX();
        double dz = end.getZ() - start.getZ();
        double lengthSquared = dx * dx + dz * dz;
        if (lengthSquared <= 0.0001) {
            return 0.0;
        }

        double px = point.getX() - start.getX();
        double pz = point.getZ() - start.getZ();
        return (px * dx + pz * dz) / lengthSquared;
    }

    private double clamp(double value) {
        return Math.max(0.0, Math.min(1.0, value));
    }

    private Location interpolate(Location start, Location end, double t) {
        double x = start.getX() + (end.getX() - start.getX()) * t;
        double y = start.getY() + (end.getY() - start.getY()) * t;
        double z = start.getZ() + (end.getZ() - start.getZ()) * t;
        return new Location(start.getWorld(), x, y, z);
    }

    private Location indicatorLocation(Player viewer, Location nextWaypoint) {
        Location playerLocation = viewer.getLocation();
        Vector forward = viewer.getEyeLocation().getDirection();
        forward.setY(0.0);
        if (forward.lengthSquared() <= 0.0001) {
            forward = direction(playerLocation, nextWaypoint);
        }
        if (forward.lengthSquared() > 0.0001) {
            forward.normalize().multiply(settings.indicatorDistance());
        }

        Location location = playerLocation.clone().add(forward);
        location.setY(playerLocation.getY() + settings.heightOffset());

        location.setYaw(indicatorYaw(playerLocation, nextWaypoint));
        location.setPitch(0.0f);
        return location;
    }

    private float indicatorYaw(Location playerLocation, Location nextWaypoint) {
        Vector pathDirection = direction(playerLocation, nextWaypoint);
        if (pathDirection.lengthSquared() <= 0.0001) {
            return playerLocation.getYaw() + (float) settings.indicatorYawOffset();
        }
        return yaw(pathDirection) + (float) settings.indicatorYawOffset();
    }

    private Vector direction(Location from, Location to) {
        return to.toVector().subtract(from.toVector()).setY(0.0);
    }

    private double horizontalDistanceSquared(Location a, Location b) {
        double dx = a.getX() - b.getX();
        double dz = a.getZ() - b.getZ();
        return dx * dx + dz * dz;
    }

    private double horizontalDistance(Location a, Location b) {
        return Math.sqrt(horizontalDistanceSquared(a, b));
    }

    private float yaw(Vector direction) {
        if (direction.lengthSquared() <= 0.0001) {
            return 0.0f;
        }
        return (float) Math.toDegrees(Math.atan2(-direction.getX(), direction.getZ()));
    }

    private boolean sameWorld(Location location, Player viewer) {
        return location != null && location.getWorld() != null && location.getWorld().equals(viewer.getWorld());
    }

    private void removeIndicator(ItemDisplay indicator, Player viewer) {
        if (indicator == null) {
            return;
        }
        if (indicator.isValid()) {
            if (viewer != null && plugin.isEnabled()) {
                viewer.hideEntity(plugin, indicator);
            }
            indicator.remove();
        }
    }
}
