package kr.antos112.addnavigation.navigation;

import kr.antos112.addnavigation.AddNavigation;
import kr.antos112.addnavigation.api.NavigationSession;
import kr.antos112.addnavigation.model.NavigationSettings;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.TextColor;
import org.bukkit.Color;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.entity.Display;
import org.bukkit.entity.Player;
import org.bukkit.entity.TextDisplay;
import org.bukkit.util.Transformation;
import org.joml.Quaternionf;
import org.joml.Vector3f;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Renders floating arrow markers that are visible only to the target player.
 */
public final class ArrowTrailRenderer {
    private final AddNavigation plugin;
    private final NavigationSettings settings;

    /**
     * Creates a renderer with plugin and display settings.
     *
     * @param plugin plugin instance
     * @param settings navigation display settings
     */
    public ArrowTrailRenderer(AddNavigation plugin, NavigationSettings settings) {
        this.plugin = plugin;
        this.settings = settings;
    }

    /**
     * Updates the visible arrow trail for a viewer.
     *
     * @param viewer player who should see the trail
     * @param session active navigation session
     * @param path raw path points generated by the pathfinder
     */
    public void render(Player viewer, NavigationSession session, List<Location> path) {
        List<Location> samples = samplePath(path, settings.arrowSpacing(), settings.maxArrows());
        syncMarkers(viewer, session, samples);
    }

    /**
     * Removes every rendered marker for the given session.
     *
     * @param session active session
     * @param viewer player who currently sees the markers
     */
    public void clearAll(NavigationSession session, Player viewer) {
        for (TextDisplay marker : new ArrayList<>(session.getMarkers())) {
            if (marker != null && marker.isValid()) {
                viewer.hideEntity(plugin, marker);
                marker.remove();
            }
        }
        session.getMarkers().clear();
    }

    private void syncMarkers(Player viewer, NavigationSession session, List<Location> samples) {
        List<TextDisplay> markers = session.getMarkers();

        while (markers.size() > samples.size()) {
            TextDisplay remove = markers.remove(markers.size() - 1);
            if (remove != null && remove.isValid()) {
                viewer.hideEntity(plugin, remove);
                remove.remove();
            }
        }

        for (int i = 0; i < samples.size(); i++) {
            Location location = samples.get(i);
            TextDisplay display;
            if (i < markers.size()) {
                display = markers.get(i);
            } else {
                display = spawnMarker(viewer.getWorld(), location);
                markers.add(display);
            }

            display.text(Component.text(settings.arrowCharacter()).color(parseColor(settings.arrowColor())));
            display.setLineWidth(200);
            display.setTextOpacity(settings.textOpacity());
            display.setShadowed(settings.shadowed());
            display.setBillboard(Display.Billboard.CENTER);
            display.setBackgroundColor(settings.transparentBackground() ? null : Color.BLACK);
            display.setViewRange(64f);
            display.setInterpolationDuration(1);
            display.setInterpolationDelay(0);
            display.setDisplayWidth(0.5f);
            display.setDisplayHeight(0.5f);
            display.setPersistent(false);
            display.setVisibleByDefault(false);
            display.setGravity(false);
            display.setTransformation(new Transformation(
                    new Vector3f(),
                    new Quaternionf(),
                    new Vector3f(0.7f, 0.7f, 0.7f),
                    new Quaternionf()
            ));

            display.teleport(location);
            viewer.showEntity(plugin, display);
        }
    }

    private TextDisplay spawnMarker(World world, Location location) {
        return world.spawn(location, TextDisplay.class, display -> {
            display.setVisibleByDefault(false);
            display.setGravity(false);
            display.setSilent(true);
            display.setPersistent(false);
            display.setBillboard(Display.Billboard.CENTER);
            display.setTeleportDuration(0);
            display.setInterpolationDuration(1);
            display.setInterpolationDelay(0);
            display.setViewRange(64f);
        });
    }

    private List<Location> samplePath(List<Location> path, double spacing, int maxMarkers) {
        if (path == null || path.isEmpty()) {
            return List.of();
        }

        List<Location> samples = new ArrayList<>();
        Location previous = path.getFirst().clone();
        samples.add(previous.clone().add(0.0, settings.heightOffset(), 0.0));

        double distanceUntilNext = spacing;

        for (int i = 1; i < path.size() && samples.size() < maxMarkers; i++) {
            Location current = path.get(i).clone();
            double segmentLength = previous.distance(current);
            if (segmentLength <= 0.0001) {
                previous = current;
                continue;
            }

            while (segmentLength >= distanceUntilNext && samples.size() < maxMarkers) {
                double t = distanceUntilNext / segmentLength;
                Location sample = interpolate(previous, current, t);
                samples.add(sample.clone().add(0.0, settings.heightOffset(), 0.0));
                previous = sample;
                segmentLength = previous.distance(current);
                distanceUntilNext = spacing;
            }

            distanceUntilNext -= segmentLength;
            previous = current;
        }

        if (samples.size() == 1 && path.size() > 1) {
            samples.add(path.get(1).clone().add(0.0, settings.heightOffset(), 0.0));
        }

        return samples;
    }

    private Location interpolate(Location a, Location b, double t) {
        double x = a.getX() + (b.getX() - a.getX()) * t;
        double y = a.getY() + (b.getY() - a.getY()) * t;
        double z = a.getZ() + (b.getZ() - a.getZ()) * t;
        return new Location(a.getWorld(), x, y, z);
    }

    private TextColor parseColor(String color) {
        if (color == null || color.isBlank()) {
            return TextColor.color(124, 255, 74);
        }
        try {
            String normalized = color.trim().toUpperCase(Locale.ROOT);
            if (normalized.startsWith("#")) {
                return TextColor.fromHexString(normalized);
            }
            return TextColor.fromHexString("#" + normalized);
        } catch (Exception ignored) {
            return TextColor.color(124, 255, 74);
        }
    }
}
